### ISSUE TITLE
set default options

### ISSUE THREAD

**Issue by bmesuere** [staaky/strip#12]
Is there a way to globally override the default options?

If I understand the code right, the only way to override the defaults is by setting them on a per image/show basis.

It would be nice to be able to say for example "always show the image from the left side, except if defined otherwise"

**Comment by chrismccoy** [comment]
you can set an array of defaults to pass over the built in ones, then you can pass a defined one via the data options

**Comment by bmesuere** [comment]
@chrismccoy to which function should I pass my default options? There doesn't seem to be an initialize of some kind.

**Comment by chrismccoy** [comment]
for new global default

    $.extend(Strip.skins.strip, {
      side: 'left'
    });

then to override per gallery/image

    <a href="urlhere" class="strip" data-strip-options="side: 'top'">Image at the top now</a>

for all the options http://www.stripjs.com/documentation/options
