### ISSUE TITLE
Dynamically changing strip-group causes weird behavior.

### ISSUE THREAD

**Issue by CptMeatball** [staaky/strip#15]
If you want to dynamically change `data-strip-group` Strip has some unusual behavior.

Usecase:

I have 50 photos, that need to be in a group `all` onload. 
User input can filter photos to a new category, which also changes the `data-strip-group`.

When users first click on a photo in the `all` group, it sorts them nice in a 50 photo group. But when clicking strip away, navigating to a new category (thus changing the `strip-group` attribute), and clicking a new photo that now belongs to a different `strip-group`, Strip removes the photos of the new group from the `all` group, and shows the `all` group instead.

When immediately filtering to a category, repeating the steps above but **avoiding the "all" category**, it works just fine. 

Code used to change attribute:
```
$(function(){
    $('.photos-container').isotope({
        itemSelector: '.photo',
        layoutMode: 'masonry'
    });
   
    $('.photo-navigation .iso-nav-btn').on('click', function(){
        filter = $(this).data('category');
        $('.photos-container').isotope({
            filter: filter
        });
        
        if(filter === "*"){
            $('.photo .strip').attr('data-strip-group', 'all');
        }else{
            $(filter).find('.strip').attr('data-strip-group', filter.substr(1));
        }
    });
});
```

I'm guessing it has something to do with the eventlistener attached to the photo elements, but I can't find a way to destroy and reattach the listiners on each filter.

**Comment by staaky** [comment]
should be fixed in 1.6.5
